title: Star Alliance
author: Marc Cornelissen
baseurl: /
domain: stichtingmakombeh
media: /media
permalink: /:title
collections_dir: content
collections:
  algemeen:
    output: true
  nieuws:
    output: true
port: 4017
sass:
  style: compressed
exclude: 
  - Gemfile
  - Gemfile.lock
  - config.codekit
  - config.rb
  - node_modules
  - patternslib/node_modules
  - Makefile
  - README.md
  - bundle-config.js
  - src/
  - stamp-npm
  - stamp-bundler
  - package.json
  - package-lock.json
  - npmshrinkwrap.json
  - webpack.config.js
  - vendor