twitter: stichtingmakombeh
title: Stichting Makombeh
author: Cornelis G. A. Kolbach
baseurl: http://www.stichtingmakombeh.nl
domain: stichtingmakombeh.nl
media: /media
permalink: /:title
prose:
  rooturl: '_posts'
  siteurl: 'http://prose.github.io/starter/'
  relativeLinks: 'http://prose.github.io/starter/links.jsonp'
  media: 'media/'
  ignore:
    - index.html
    - _config.yml
    - /_layouts
    - /_includes
    - /media
    - /lib
    - /work
    - /style
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "case"
      - name: "title"
        field:
          element: "text"
          placeholder: "Title"
          label: "Document title"
      - name: "summary"
        field:
          element: "text"
          label: "Document summary"
      - name: "tags"
        field:
          element: "multiselect"
          label: "Add Tags"
          placeholder: "Choose Tags"
          alterable: true
          options:
            - name: 'Financials'
              value: 'financials'
            - name: 'Mobiel'
              value: 'mobiel'
            - name: 'Overheid'
              value: 'overheid'
            - name: 'Service design'
              value: 'service-design'
      - name: "width"
        field:
          element: "number"
          label: "Card width on homepage"
          help: "Choose a number from 1 to 3 which represents the column width of the card on the homepage."
          placeholder: 1
      - name: "card_appearance"
        field:
          element: "select"
          label: "Card appearance on homepage"
          placeholder: "link"
          options:
            - name: 'Link to a page'
              value: link
            - name: 'Expandable card'
              value: 'expand'
            - name: 'Hide from homepage'
              value: 'hide'
      - name: "card_background_image"
        field:
          element: "text"
          label: "Card background image"
      - name: "colour"
        field:
          element: "select"
          label: "Card and page colour"
          options:
            - name: "Light blue"
              value: "A9DBE6"
            - name: "Medium blue"
              value: "3399CC"
            - name: "Dark blue"
              value: "245F7D"
            - name: "Light green"
              value: "CFE4C3"
            - name: "Medium green"
              value: "66CC66"
            - name: "Dark green"
              value: "43733F"
            - name: "Light orange"
              value: "F8CB9A"
            - name: "Medium orange"
              value: "FF9933"
            - name: "Dark orange"
              value: "945D20"
            - name: "Light red"
              value: "F5CBCC"
            - name: "Medium red"
              value: "FF3333"
            - name: "Dark red"
              value: "8D2720"
    _posts/static:
      - name: "layout"
        field:
          element: "hidden"
          value: "page"
      - name: "permalink"
        field:
          element: "text"
          label: "Permalink"
          value: ""